name: hasher
version: '1.2'
summary: This program hashes text that you type whith my algorithm.
description: I had nothing to do so I created this program. To dehash use dehasher. To run type "hasher" in the terminal.
grade: stable # devel # must be 'stable' to release into candidate/stable channels
confinement: strict # use 'strict' once you have the right plugs and slots
base: core18

apps:
    hasher:
        command: python3 $SNAP/hasher.py
        plugs: [home, gsettings, network]

parts:
  copy-stuff:
    plugin: dump
    source: .
  hasher:
    plugin: python
    python-version: python3
    source: .
    stage-packages:
        - libssl-dev
        - libjpeg-dev
        - libtiff-dev
        - libsdl1.2-dev
        - libnotify-dev
        - freeglut3
        - ibus-gtk3
        - libwebkitgtk-3.0-0
        - zlib1g
        - libsm6
        - libpulse0
        - libslang2
        - libsdl1.2debian
